import cv2 as cv
import math
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Arc

FIELD_COLOR = (255,0,255)

MARGIN_PX = 30  # pixel margin around the field in the generated image
FIELD_IMG_HEIGHT_PX = 500


def _field_image_scale(field_config):
    return (FIELD_IMG_HEIGHT_PX - 2 * MARGIN_PX) / field_config.height

def field_image_hw(field_config):
    """Return (height_px, width_px) of the image generated by render_field_image."""
    scale = _field_image_scale(field_config)
    return FIELD_IMG_HEIGHT_PX, int(field_config.width * scale + 2 * MARGIN_PX)


def render_field_image(field_config):
    """
    Generate a top-down field image from field_config (values in mm).
    Returns:
        img_bgr: np.ndarray (H, W, 3) uint8, BGR image
        corners_px: list of default calibration [x, y] in image space (5 points: top band + bottom symmetry)
    """
    fc = field_config
    hw = fc.xlimit
    hh = fc.ylimit

    # compute image size keeping aspect ratio
    scale = _field_image_scale(field_config)  # px/mm
    img_h_px, img_w_px = field_image_hw(field_config)  # we compute scale twice but w/e, it's just a little arithmetic

    fig, ax = plt.subplots(figsize=(img_w_px / 100, img_h_px / 100), dpi=100)
    ax.set_xlim(-hw - MARGIN_PX / scale, hw + MARGIN_PX / scale)
    ax.set_ylim(-hh - MARGIN_PX / scale, hh + MARGIN_PX / scale)
    ax.set_aspect('equal')
    ax.axis('off')
    fig.patch.set_facecolor('green')
    ax.set_facecolor('green')

    lw = 2
    col = 'white'

    def rect(x, y, w, h):
        ax.add_patch(patches.Rectangle((x, y), w, h, linewidth=lw, edgecolor=col, facecolor='none'))

    # field border
    rect(-hw, -hh, fc.width, fc.height)
    # halfway line
    ax.plot([0, 0], [-hh, hh], color=col, linewidth=lw)
    # center circle
    ax.add_patch(plt.Circle((0, 0), fc.center_radius, linewidth=lw, edgecolor=col, facecolor='none'))
    # center mark
    ax.plot(0, 0, 'o', color=col, markersize=3)

    # goal areas
    ga_w = fc.goal_area_width
    ga_h = fc.goal_area_ylimit
    rect(-hw, -ga_h, ga_w, ga_h * 2)
    rect(hw - ga_w, -ga_h, ga_w, ga_h * 2)

    # penalty areas
    pa_w = fc.penalty_area_width
    pa_h = fc.penalty_area_ylimit
    rect(-hw, -pa_h, pa_w, pa_h * 2)
    rect(hw - pa_w, -pa_h, pa_w, pa_h * 2)

    # penalty marks
    pmx = fc.penalty_mark_x
    ax.plot(-pmx, 0, '+', color=col, markersize=6, markeredgewidth=lw)
    ax.plot(pmx, 0, '+', color=col, markersize=6, markeredgewidth=lw)

    fig.tight_layout(pad=0)
    fig.canvas.draw()
    buf = np.frombuffer(fig.canvas.buffer_rgba(), dtype=np.uint8)
    buf = buf.reshape(fig.canvas.get_width_height()[::-1] + (4,))
    plt.close(fig)

    img_bgr = cv.cvtColor(buf, cv.COLOR_RGBA2BGR)

    # resize to exact target size
    img_bgr = cv.resize(img_bgr, (img_w_px, img_h_px))

    # compute corner pixel positions (field corners in image coords)
    def mm_to_px(x_mm, y_mm):
        px_x = int((x_mm + hw) * scale + MARGIN_PX)
        px_y = int(img_h_px - ((y_mm + hh) * scale + MARGIN_PX))
        return [px_x, px_y]

    # Default calibration: 5 points so left AND right bottom penalty corners both
    # constrain the warp (4 points with only one side in basso lascia libera la destra).
    pa_w = fc.penalty_area_width
    pa_h = fc.penalty_area_ylimit
    ga_w = fc.goal_area_width
    ga_h = fc.goal_area_ylimit
    cr = fc.center_radius
    pm = fc.penalty_mark_distance
    corners_px = [
        mm_to_px(-hw,  hh),          # top-left corner
        mm_to_px(0, hh),             # top middle
        mm_to_px(hw,  hh),           # top-right corner
        mm_to_px(hw, pa_h),          # top-right of right penalty area
        mm_to_px(hw - pa_w, pa_h),   # top-left of right penalty area
        mm_to_px(-hw + pa_w, pa_h),  # top-right of left penalty area
        mm_to_px(-hw, pa_h),         # top-left of left penalty area
        mm_to_px(-hw, ga_h),         # top-left of left goal area
        mm_to_px(-hw + ga_w, ga_h),  # top-right of left goal area
        mm_to_px(0, cr),             # top of center circle
        mm_to_px(hw - ga_w, ga_h),   # top-left of right goal area
        mm_to_px(hw, ga_h),          # top-right of right goal area
        mm_to_px(hw - pm, 0),        # right penalty mark
        mm_to_px(0, 0),              # center
        mm_to_px(-hw + pm, 0),       # left penalty mark
        mm_to_px(-hw, -ga_h),        # bottom-left of left goal area
        mm_to_px(-hw + ga_w, -ga_h), # bottom-right of left goal area
        mm_to_px(0, -cr),            # bottom of center circle
        mm_to_px(hw - ga_w, -ga_h),  # bottom-left of right goal area
        mm_to_px(hw, -ga_h),         # bottom-right of right goal area
        mm_to_px(hw, -pa_h),         # bottom-right of right penalty area
        mm_to_px(hw - pa_w, -pa_h),  # bottom-left of right penalty area
        mm_to_px(-hw + pa_w, -pa_h), # bottom-right of left penalty area
        mm_to_px(-hw, -pa_h),        # bottom-left of left penalty area
        mm_to_px(-hw, -hh),          # bottom-left corner
        mm_to_px(0, -hh),            # bottom middle
        mm_to_px(hw, -hh),           # bottom-right corner
    ]

    return img_bgr, corners_px

TEAM_COLORS = {
    "black":   (  0,   0,   0),
    "red":     (  0,   0, 255),
    "green":   (  0, 255,   0),
    "blue":    (255,   0,   0),
    "yellow":  (  0, 250, 250),
    "orange":  (  0, 140, 255),
    "brown":   ( 19,  69, 139),
    "purple":  (180,   0, 180),
    "gray":    (128, 128, 128),
    "white":   (255, 255, 255),
    "unknown": (100, 100, 100),  # CNN catch-all / ambiguous jersey
    "ball":    (255, 255, 255),  # special value for ball tracks
}

class Drawer:
    def __init__(self, config, calibration):
        self.transforms = config.make_transforms()
        self.calibration = calibration
        self.fc = config.field_config
        self.wfield_segments = config.drawing.warped_field_segment_resolution
        self._do_warp = True

    @classmethod
    def NullDrawer(cls, config):
        nd = cls(config, None)
        nd._do_warp = False
        return nd

    def set_warp_params(self, calibration):
        assert self._do_warp, "Trying to set camera calibration (warp) on non-warping Drawer."
        self.calibration = calibration

    def centered_rect(self, frame, pos, half_sizes, color, thickness, **kwargs):
        p1 = (pos[0]-half_sizes[0], pos[1]-half_sizes[1])
        p2 = (pos[0]+half_sizes[0], pos[1]+half_sizes[1])
        cv.rectangle(frame, p1, p2, color, thickness, **kwargs)

    def multicolor_rect(self, frame, p1, p2, colors, thickness, **kwargs):
        points = (
            p1,
            (p1[0], p2[1]),
            p2,
            (p2[0], p1[1])
        )
        colors = list(colors)
        for i in range(4):
            col = TEAM_COLORS[colors[i % len(colors)]]
            cv.line(frame, points[i-1], points[i], col, thickness, **kwargs)

    def cross(self, frame, pos, half_sizes, color, thickness, **kwargs):
        p1 = (pos[0]-half_sizes[0], pos[1]-half_sizes[1])
        p2 = (pos[0]+half_sizes[0], pos[1]+half_sizes[1])
        cv.line(frame, p1, p2, color, thickness, **kwargs)
        p3 = (pos[0]-half_sizes[0], pos[1]+half_sizes[1])
        p4 = (pos[0]+half_sizes[0], pos[1]-half_sizes[1])
        cv.line(frame, p3, p4, color, thickness, **kwargs)

    def multiline_text( img, lines, origin, line_distance, fontFace, fontScale, color, thickness, **kwargs):
        for i, line in enumerate(lines):
            position = (origin[0], origin[1] + i * line_distance)
            cv.putText(img, line, position, fontFace, fontScale, color, thickness, **kwargs)

    def warped_field(self, frame, line_color=None, thickness=2):
        """Draw pitch lines in field image space (used for plan view and schematic overlays)."""
        c = FIELD_COLOR if line_color is None else line_color
        hw, hh = self.fc.xlimit, self.fc.ylimit
        top_left = (-hw, hh)
        top_right = (hw, hh)
        bottom_left = (-hw, -hh)
        bottom_right = (hw, -hh)
        self.warped_polygon(frame, [top_left, top_right, bottom_right, bottom_left], self.wfield_segments, c, thickness)

        top_center = (0, hh)
        bottom_center = (0, -hh)
        center_cross_1 = (-100, 0)
        center_cross_2 = (100, 0)
        self.warped_line(frame, top_center, bottom_center, 4, c, thickness)
        self.warped_line(frame, center_cross_1, center_cross_2, 1, c, thickness)

        NUM_PTS = self.wfield_segments
        circle_points = [
            self.position_to_image_pipeline(
                math.cos(2*math.pi * i/NUM_PTS) * self.fc.center_radius,
                math.sin(2*math.pi * i/NUM_PTS) * self.fc.center_radius,
            ) for i in range(NUM_PTS)
        ]
        for i in range(NUM_PTS):
            cv.line(frame, circle_points[i], circle_points[(i+1)%NUM_PTS], c, thickness)

        gaw, gah = self.fc.goal_area_width, self.fc.goal_area_ylimit
        goal1_top_left = (-hw, gah)
        goal1_top_right = (-hw+gaw, gah)
        goal1_bottom_left = (-hw, -gah)
        goal1_bottom_right = (-hw+gaw, -gah)
        self.warped_polygon(frame, [goal1_top_left, goal1_top_right, goal1_bottom_right, goal1_bottom_left], self.wfield_segments, c, thickness, closed=False)
        goal2_top_left = (hw-gaw, gah)
        goal2_top_right = (hw, gah)
        goal2_bottom_left = (hw-gaw, -gah)
        goal2_bottom_right = (hw, -gah)
        self.warped_polygon(frame, [goal2_top_right, goal2_top_left, goal2_bottom_left, goal2_bottom_right], self.wfield_segments, c, thickness, closed=False)

        paw, pah = self.fc.penalty_area_width, self.fc.penalty_area_ylimit
        penalty1_top_left = (-hw, pah)
        penalty1_top_right = (-hw+paw, pah)
        penalty1_bottom_left = (-hw, -pah)
        penalty1_bottom_right = (-hw+paw, -pah)
        self.warped_polygon(frame, [penalty1_top_left, penalty1_top_right, penalty1_bottom_right, penalty1_bottom_left], self.wfield_segments, c, thickness, closed=False)
        penalty2_top_left = (hw-paw, pah)
        penalty2_top_right = (hw, pah)
        penalty2_bottom_left = (hw-paw, -pah)
        penalty2_bottom_right = (hw, -pah)
        self.warped_polygon(frame, [penalty2_top_right, penalty2_top_left, penalty2_bottom_left, penalty2_bottom_right], self.wfield_segments, c, thickness, closed=False)

        pmx = self.fc.penalty_mark_x
        penmark1_left = (-pmx-100, 0)
        penmark1_right = (-pmx+100, 0)
        penmark1_top = (-pmx, 100)
        penmark1_bottom = (-pmx, -100)
        self.warped_line(frame, penmark1_left, penmark1_right, 1, c, thickness)
        self.warped_line(frame, penmark1_top, penmark1_bottom, 1, c, thickness)
        penmark2_left = (pmx-100, 0)
        penmark2_right = (pmx+100, 0)
        penmark2_top = (pmx, 100)
        penmark2_bottom = (pmx, -100)
        self.warped_line(frame, penmark2_left, penmark2_right, 1, c, thickness)
        self.warped_line(frame, penmark2_top, penmark2_bottom, 1, c, thickness)

    def warped_line(self, frame, p1, p2, segments, color, thickness, **kwargs):
        ps = np.linspace(np.array(p1), np.array(p2), segments+1).astype(int)
        ps_warped = [self.position_to_image_pipeline(p[0], p[1]) for p in ps]
        for i in range(segments):
            cv.line(frame, ps_warped[i], ps_warped[i+1], color, thickness, **kwargs)

    def warped_polygon(self, frame, verts, segments, color, thickness, closed=True, **kwargs):
        for i in range(len(verts)):
            if not closed and i == len(verts)-1:
                continue
            self.warped_line(frame, verts[i], verts[(i+1)%len(verts)], segments, color, thickness, **kwargs)

    def flip_border(self, frame, pos, radius, thickness, col1=(255,255,255), col2=(0,0,0), **kwargs):
        cv.ellipse(frame, pos, (radius, radius), 0,   0,  90, col1, thickness, **kwargs)
        cv.ellipse(frame, pos, (radius, radius), 0,  90, 180, col2, thickness, **kwargs)
        cv.ellipse(frame, pos, (radius, radius), 0, 180, 270, col1, thickness, **kwargs)
        cv.ellipse(frame, pos, (radius, radius), 0, 270, 360, col2, thickness, **kwargs)

    def position_to_image_pipeline(self, x, y, flipped=False):
        pos = [x, y]  # field
        if flipped:
            pos = [-x, -y]
        pos = [self.transforms.field_to_image_x(pos), self.transforms.field_to_image_y(pos)]  # MARIO (warped with homography and radial)

        # simple drawers that are just for drawing plain, undistorted fields stop here
        if not self._do_warp:
            return (int(pos[0]), int(pos[1]))

        # drawers intended for warped stuff apply the distortion
        assert self.calibration is not None, "Forgot to set calibration for warping Drawer"
        pos = np.array([pos+[0]], dtype=np.float32)
        pos, _ = self.calibration.project_points(pos)
        pos = pos[0][0]
        CLAMP = 100000
        pos = (int(np.clip(pos[0], -CLAMP, CLAMP)), int(np.clip(pos[1], -CLAMP, CLAMP)))
        return pos
