# some robot-specific stuff goes here, for now it's just sincrolog

sincrolog:
  distance_threshold_initial: 1050

  future_analysis_window_ms: 8000
  future_sample_rate: 30

  current_distance_weight: 1.0
  max_assignment_cost: 700

  max_search_radius: 2000
  max_robot_speed: 1000

  max_ball_age: 2.0
  max_ball_jump: 600

  distance_break_threshold_max: 1000
  distance_better_factor: 0.65

  flip_dist_threshold: 550
