#!/usr/bin/env python3
"""
Train YOLOv12 on a dataset (e.g. generated by collect_dataset_sam3.py).

Usage:
  python scripts/train_yolo.py --data data/Final_GO/mario_1/sam3_dataset/dataset.yaml
  python scripts/train_yolo.py --data dataset.yaml --epochs 200 --batch 8 --imgsz 1280
  python scripts/train_yolo.py --data dataset.yaml --model yolo12l.pt --epochs 300

Fine-tune sulla palla senza “dimenticare” i robot (stesso nc e stesso ordine classi di MARIO):
  1) Unisci nel dataset **tutte** le immagini/label vecchie **più** i nuovi frame etichettati
     (robot + palla dove serve). Non usare **solo** palla: il modello deve rivedere spesso
     anche la classe robot.
  2) In dataset.yaml mantieni identici ``nc`` e ``names`` (es. 0=robot, 1=ball come in detection).
  3) Partenza dai pesi attuali, non da yolo12n.pt da zero::
       --model data/models/yolo12_sam3.pt
  4) Fine-tune conservativo (esempio)::
       --epochs 80 --lr0 0.0001 --freeze 10 --oversample --patience 25 --imgsz 960
     ``--freeze 10`` aggiorna soprattutto testa/neck; ``--lr0`` basso limita il drift sui robot.
     ``--oversample`` duplica le immagini che contengono la classe minoritaria (spesso la palla).
  5) Valuta su ``runs/detect/.../val`` e confronta mAP per classe; se il robot cala, riduci epoch,
     abbassa ancora lr0 o aumenta freeze.
"""

import argparse
from pathlib import Path
from ultralytics import YOLO


def parse_args():
    parser = argparse.ArgumentParser(description="Train YOLOv12 on dataset")
    parser.add_argument("--data", "-d", type=Path, required=True,
                        help="Path to dataset.yaml")
    parser.add_argument("--model", "-m", type=str, default="yolo12m.pt",
                        help="Pretrained model (default: yolo12m.pt)")
    parser.add_argument("--epochs", "-e", type=int, default=100,
                        help="Number of epochs (default: 100)")
    parser.add_argument("--batch", "-b", type=int, default=16,
                        help="Batch size (default: 16)")
    parser.add_argument("--imgsz", type=int, default=640,
                        help="Image size (default: 640)")
    parser.add_argument("--device", type=str, default=None,
                        help="Device (default: auto)")
    parser.add_argument("--name", "-n", type=str, default="sam3_yolov12",
                        help="Run name (default: sam3_yolov12)")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from last checkpoint")
    parser.add_argument("--val-split", type=float, default=0.15,
                        help="Fraction of data for validation (default: 0.15)")
    parser.add_argument("--exclude-classes", nargs="+", type=int, default=None,
                        help="Class IDs to exclude from training (e.g. --exclude-classes 2)")
    parser.add_argument("--oversample", action="store_true",
                        help="Oversample images containing minority classes to balance dataset")
    parser.add_argument("--freeze", type=int, default=None,
                        help="Freeze first N layers (e.g. 10) for conservative fine-tuning")
    parser.add_argument("--lr0", type=float, default=None,
                        help="Initial LR (lower = less forgetting, e.g. 1e-4)")
    parser.add_argument("--patience", type=int, default=None,
                        help="Early stopping patience (epochs without val improvement)")
    parser.add_argument("--warmup-epochs", type=float, default=None,
                        help="LR warmup epochs")
    parser.add_argument("--hyp", type=Path, default=None,
                        help="Optional Ultralytics hyperparameters YAML (overrides lr0 if set inside)")
    return parser.parse_args()


def split_dataset(data_path: Path, val_fraction: float):
    """
    Split images/labels into train/val if not already split.
    Creates train/ and val/ subdirs inside images/ and labels/.
    Updates dataset.yaml accordingly.
    """
    import random
    import shutil
    import yaml

    images_dir = data_path.parent / "images"
    labels_dir = data_path.parent / "labels"

    # Already split?
    if (images_dir / "train").exists() and (images_dir / "val").exists():
        print("Dataset already split into train/val.")
        return

    all_images = sorted(images_dir.glob("*.jpg"))
    if not all_images:
        all_images = sorted(images_dir.glob("*.png"))
    if not all_images:
        print("No images found!")
        return

    random.seed(42)
    random.shuffle(all_images)
    val_count = max(1, int(len(all_images) * val_fraction))
    val_images = all_images[:val_count]
    train_images = all_images[val_count:]

    for split, split_images in [("train", train_images), ("val", val_images)]:
        (images_dir / split).mkdir(exist_ok=True)
        (labels_dir / split).mkdir(exist_ok=True)
        for img_path in split_images:
            label_path = labels_dir / img_path.with_suffix(".txt").name
            shutil.move(str(img_path), str(images_dir / split / img_path.name))
            if label_path.exists():
                shutil.move(str(label_path), str(labels_dir / split / label_path.name))

    # Update dataset.yaml
    with open(data_path) as f:
        ds = yaml.safe_load(f)
    ds["train"] = "images/train"
    ds["val"] = "images/val"
    with open(data_path, "w") as f:
        yaml.dump(ds, f, default_flow_style=False)

    print(f"Split: {len(train_images)} train, {len(val_images)} val")


def filter_classes(data_path: Path, exclude: list):
    """
    Remove excluded classes from label files and remap remaining class IDs.
    Also updates dataset.yaml with the new class list.
    """
    import yaml

    with open(data_path) as f:
        ds = yaml.safe_load(f)

    old_names = ds.get("names", [])
    # Build remap: old_id -> new_id (skipping excluded)
    remap = {}
    new_names = []
    new_id = 0
    for old_id, name in enumerate(old_names):
        if old_id not in exclude:
            remap[old_id] = new_id
            new_names.append(name)
            new_id += 1

    print(f"Excluding classes {exclude}: {[old_names[i] for i in exclude if i < len(old_names)]}")
    print(f"Remaining: {new_names}")

    labels_dir = data_path.parent / "labels"
    count = 0
    for label_file in labels_dir.rglob("*.txt"):
        lines = label_file.read_text().strip().split("\n")
        new_lines = []
        for line in lines:
            if not line.strip():
                continue
            parts = line.split()
            cls_id = int(parts[0])
            if cls_id in remap:
                parts[0] = str(remap[cls_id])
                new_lines.append(" ".join(parts))
        label_file.write_text("\n".join(new_lines) + "\n" if new_lines else "")
        count += 1

    # Update dataset.yaml
    ds["names"] = new_names
    ds["nc"] = len(new_names)
    with open(data_path, "w") as f:
        yaml.dump(ds, f, default_flow_style=False)

    print(f"Filtered {count} label files. New nc={len(new_names)}")


def clean_oversample(data_path: Path):
    """Remove all previously oversampled images and labels (_ov* files)."""
    labels_dir = data_path.parent / "labels"
    images_dir = data_path.parent / "images"

    removed = 0
    for d in [images_dir, labels_dir]:
        for f in d.rglob("*_ov*"):
            if f.is_file():
                f.unlink()
                removed += 1

    if removed:
        print(f"Cleaned {removed} old oversample files.")


def oversample_minority(data_path: Path):
    """
    Oversample images that contain minority classes by duplicating them
    in the training set. Counts instances per class, then duplicates
    images containing rare classes so that instance counts are roughly balanced.
    """
    import shutil
    from collections import Counter

    labels_dir = data_path.parent / "labels"
    images_dir = data_path.parent / "images"

    # Work on train split
    train_labels = labels_dir / "train"
    train_images = images_dir / "train"
    if not train_labels.exists():
        train_labels = labels_dir
        train_images = images_dir

    # Count instances per class and track which images have which classes
    class_counts = Counter()
    image_classes = {}  # filename -> set of class ids

    for label_file in sorted(train_labels.glob("*.txt")):
        classes_in_file = set()
        content = label_file.read_text().strip()
        if not content:
            continue
        for line in content.split("\n"):
            if line.strip():
                cls_id = int(line.split()[0])
                class_counts[cls_id] += 1
                classes_in_file.add(cls_id)
        image_classes[label_file.stem] = classes_in_file

    if not class_counts:
        print("No labels found for oversampling.")
        return

    print(f"Instance counts before oversample: {dict(class_counts)}")

    max_count = max(class_counts.values())

    # For each minority class, figure out how many times to duplicate its images
    # to roughly match the majority class
    minority_classes = {
        cls: max_count / count
        for cls, count in class_counts.items()
        if count < max_count
    }

    if not minority_classes:
        print("Dataset already balanced.")
        return

    ratios_str = {cls: f"{ratio:.1f}x" for cls, ratio in minority_classes.items()}
    print(f"Oversample ratios: {ratios_str}")

    # Find images that contain each minority class
    duplicated = 0
    for cls_id, ratio in minority_classes.items():
        n_copies = int(ratio) - 1  # -1 because original already exists
        if n_copies < 1:
            continue

        imgs_with_class = [
            name for name, classes in image_classes.items()
            if cls_id in classes
        ]

        for name in imgs_with_class:
            for copy_i in range(1, n_copies + 1):
                new_name = f"{name}_ov{cls_id}c{copy_i}"

                # Copy image
                for ext in [".jpg", ".png"]:
                    src_img = train_images / f"{name}{ext}"
                    if src_img.exists():
                        shutil.copy2(str(src_img), str(train_images / f"{new_name}{ext}"))
                        break

                # Copy label
                src_label = train_labels / f"{name}.txt"
                if src_label.exists():
                    shutil.copy2(str(src_label), str(train_labels / f"{new_name}.txt"))

                duplicated += 1

    # Recount
    new_counts = Counter()
    for label_file in train_labels.glob("*.txt"):
        content = label_file.read_text().strip()
        if not content:
            continue
        for line in content.split("\n"):
            if line.strip():
                new_counts[int(line.split()[0])] += 1

    print(f"Added {duplicated} duplicated images.")
    print(f"Instance counts after oversample: {dict(new_counts)}")


def main():
    args = parse_args()

    if not args.data.exists():
        print(f"ERROR: {args.data} not found")
        return

    print(f"Splitting dataset ({args.val_split:.0%} val)...")
    split_dataset(args.data, args.val_split)

    if args.exclude_classes:
        filter_classes(args.data, args.exclude_classes)

    clean_oversample(args.data)
    if args.oversample:
        oversample_minority(args.data)

    print(f"Loading {args.model}...")
    model = YOLO(args.model)

    train_args = dict(
        data=str(args.data.resolve()),
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        name=args.name,
        exist_ok=True,
        verbose=True,
    )
    if args.device:
        train_args["device"] = args.device
    if args.resume:
        train_args["resume"] = True
    if args.freeze is not None:
        train_args["freeze"] = args.freeze
    if args.lr0 is not None:
        train_args["lr0"] = args.lr0
    if args.patience is not None:
        train_args["patience"] = args.patience
    if args.warmup_epochs is not None:
        train_args["warmup_epochs"] = args.warmup_epochs
    if args.hyp is not None:
        if not args.hyp.exists():
            print(f"ERROR: hyp file not found: {args.hyp}")
            return
        train_args["hyp"] = str(args.hyp.resolve())

    print(f"Training: {args.epochs} epochs, batch={args.batch}, imgsz={args.imgsz}")
    if args.freeze is not None:
        print(f"  freeze={args.freeze}")
    if args.lr0 is not None:
        print(f"  lr0={args.lr0}")
    results = model.train(**train_args)

    print(f"\nDone! Best weights: {results.save_dir}/weights/best.pt")


if __name__ == "__main__":
    main()
