mario_postprocessing:
  min_robot_persistence_secs: 0.5
  max_secs_for_moving_ball_interp: 1
  max_secs_for_still_ball_interp: 10
  max_field_dist_for_still_ball_interp: 100
  max_frame_lookup_for_velocity: 5
  trackcolor_window_length_secs: 2
  color_ambiguity_factor: 0.75
  neotrack_unambiguous_length_secs: 3.3
